### PR TITLE
Add static prerendered versions of the various readme badges

### PR DESCRIPTION
**Pull request by gwynne**
Like it says. Also stashes away the un-merged versions of the custom logos.

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
LGTM - how are these generated? We could store the source files/scripts in this repo

**Comment by gwynne** [comment]
There's no actual process involved, it's just "grab the source from those horribly long URLs that contain the Base64 custom logos, replace the embedded Base64 with the un-encoded inline SVG (optional), and save"

**Comment by gwynne** [comment]
The source of the custom logo icons is included in this PR

**Comment by gwynne** [comment]
I'll add a list of the URLs used to generate the badges

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
